export default {
  id: "keys",
  title: "Services à clé API",
  description: "Clés gratuites, à créer une fois chez le fournisseur.",
  services: [
    {
      type: "tisseo",
      label: "Tisséo",
      icon: "clock",
      summary: "Prochains passages aux arrêts favoris (transports toulousains).",
      settingsKey: "tisseoSettings",
      settings: {
        title: "Tisséo",
        sections: [
          {
            id: "key",
            title: "Clé API",
            fields: [{ name: "apiKey", label: "Clé API Tisséo", type: "password", required: true }],
            submitLabel: "Enregistrer la clé",
            submit: (api, v) => api.saveTisseoSettings(v.apiKey),
            clearLabel: "Effacer la clé",
            clear: (api) => api.clearTisseoSettings(),
            canClear: (s) => s.configured,
          },
          {
            id: "stop",
            title: "Arrêt favori",
            fields: [{ name: "stop", label: "Nom de l'arrêt", placeholder: "Jean Jaurès", required: true }],
            submitLabel: "Ajouter aux favoris",
            submit: (api, v) => api.connectTisseo(v.stop),
            requiresConfigured: true,
            hint: "Plusieurs arrêts peuvent être ajoutés : leurs prochains passages sont fusionnés automatiquement.",
          },
        ],
        doc: "Clé gratuite (voir README.md, section Tisséo).",
      },
    },
    {
      type: "ors",
      label: "Itinéraires",
      icon: "link",
      summary: "Temps de trajet et itinéraires (OpenRouteService).",
      settingsKey: "orsSettings",
      noAccounts: true,
      settings: {
        title: "Itinéraires (OpenRouteService)",
        sections: [
          {
            id: "key",
            title: "Clé API",
            fields: [{ name: "apiKey", label: "Clé API OpenRouteService", type: "password", required: true }],
            submitLabel: "Enregistrer la clé",
            submit: (api, v) => api.saveOrsSettings(v.apiKey),
            clearLabel: "Effacer la clé",
            clear: (api) => api.clearOrsSettings(),
            canClear: (s) => s.configured,
          },
          {
            id: "home",
            title: "Adresse du domicile",
            fields: [
              { name: "address", label: "Adresse", placeholder: "12 rue de la Paix, Toulouse", required: true },
            ],
            submitLabel: "Enregistrer le domicile",
            submit: (api, v) => api.saveHomeAddress(v.address),
            clearLabel: "Effacer",
            clear: (api) => api.clearHomeAddress(),
            canClear: (s) => !!s.home_address,
            hint: "Origine par défaut quand vous ne donnez que la destination (« combien de temps pour aller à X ? »).",
          },
        ],
        doc: "Clé gratuite et sans facturation, sur openrouteservice.org (voir README.md, section Itinéraires).",
      },
    },
    {
      type: "brave",
      label: "Recherche web",
      icon: "search",
      summary: "Chercher sur le web et résumer une page pour répondre à une question d'actualité.",
      settingsKey: "braveSettings",
      noAccounts: true,
      settings: {
        title: "Recherche web (Brave Search)",
        sections: [
          {
            id: "key",
            title: "Clé API",
            fields: [{ name: "apiKey", label: "Clé API Brave Search", type: "password", required: true }],
            submitLabel: "Enregistrer la clé",
            submit: (api, v) => api.saveBraveSettings(v.apiKey),
            clearLabel: "Effacer la clé",
            clear: (api) => api.clearBraveSettings(),
            canClear: (s) => s.configured,
          },
        ],
        doc: "Clé gratuite (2000 requêtes/mois), sur brave.com/search/api (voir README.md, section Recherche web).",
      },
    },
  ],
};
